// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/MisakaTAT/GTerm/backend/initialize"
	"github.com/MisakaTAT/GTerm/backend/services"
)

// Injectors from wire.go:

func NewApp() *App {
	httpListenerPort := initialize.InitHTTPServer()
	logger := initialize.InitZap()
	terminalSrv := &services.TerminalSrv{
		HTTPListenerPort: httpListenerPort,
		Logger:           logger,
	}
	preferencesSrv := &services.PreferencesSrv{
		Logger: logger,
	}
	query := initialize.InitDatabase()
	groupSrv := &services.GroupSrv{
		Logger: logger,
		Query:  query,
	}
	app := &App{
		HTTPListenerPort: httpListenerPort,
		Logger:           logger,
		TerminalSrv:      terminalSrv,
		PreferencesSrv:   preferencesSrv,
		GroupSrv:         groupSrv,
	}
	return app
}
