/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConnectionTabs: typeof import('./components/ConnectionTabs.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
