// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q          = new(Query)
	Connection *connection
	Credential *credential
	Group      *group
	Metadata   *metadata
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Connection = &Q.Connection
	Credential = &Q.Credential
	Group = &Q.Group
	Metadata = &Q.Metadata
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:         db,
		Connection: newConnection(db, opts...),
		Credential: newCredential(db, opts...),
		Group:      newGroup(db, opts...),
		Metadata:   newMetadata(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Connection connection
	Credential credential
	Group      group
	Metadata   metadata
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:         db,
		Connection: q.Connection.clone(db),
		Credential: q.Credential.clone(db),
		Group:      q.Group.clone(db),
		Metadata:   q.Metadata.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:         db,
		Connection: q.Connection.replaceDB(db),
		Credential: q.Credential.replaceDB(db),
		Group:      q.Group.replaceDB(db),
		Metadata:   q.Metadata.replaceDB(db),
	}
}

type queryCtx struct {
	Connection IConnectionDo
	Credential ICredentialDo
	Group      IGroupDo
	Metadata   IMetadataDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Connection: q.Connection.WithContext(ctx),
		Credential: q.Credential.WithContext(ctx),
		Group:      q.Group.WithContext(ctx),
		Metadata:   q.Metadata.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
